### PR TITLE
Generate marble diagrams as part of build

### PR DESCRIPTION
**Pull request by jroper**
As discussed in the MicroProfile Reactive weekly hangout, I've deleted all the marble diagram PNGs from the repo, and instead ensured they are built by Maven. This is using the Maven frontend plugin to download and install node and npm, and then running the script using npm. The diagrams are generated at the last possible minute before they are needed, that is, in the `prepare-package` phase.

### CODE REVIEW

**Comment by jroper** [comment]
Looking into this a bit more - we don't necessarily need Chrome to create the SVG, we can use a library called svgdom to run it directly on node. However, converting svg to png may be a problem, because fonts. SVG doesn't support (well, there was an extension but nothing supports it anymore) embedding fonts. You refer to a font by its name, and then your system (or browser) must have that font installed (in the case of a browser, could be linked to from the page). So, how do we convert svg to png? Most of the tools out there use a headless browser, which brings us back to the same problem. The only tool that doesn't is imagemagick. But does the CI server have imagemagick installed? I doubt it. And the only binaries the official site offers are rpms. Plus then there's the problem of getting our fonts into imagemagick, from what I've read, it just uses system fonts, and custom fonts are not straight forward.

So I think headless Chrome really is the simplest option, we just need its dependencies installed.

**Comment by jroper** [comment]
I raised an issue with the Eclipse CI team, and they said that it's too high a maintenance burden to install libnss3:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=537949

What they did say is that later this year, they will be making new infrastructure available as part of the CBI that will allow running builds in docker images, this would allow us to use a docker image with libnss installed.

I looked in more detail at whether it's possible to create a statically linked Chromium - everything I've read indicates it's not, libnss is apparently impossible to statically link to.

I also had a go at creating the diagrams without running in a browser, using svgdom. The diagrams don't render properly, it appears svgdom isn't reliable enough to do things like calculate the extents of bounding boxes around text properly.

So, I'm closing this PR for now. I'm also not sure 100% sure whether the custom docker image option will be viable when it's available, the problem is, we still want to use the normal MicroProfile release build, is that going to use our custom image with the dependencies installed? Maybe we can convince the rest of the MicroProfile community to use it. Not sure.

This would all be so much easier if we could just use Travis :/

**Comment by jroper** [comment]
I'm reopening this pull request. I've modified the build so that the diagrams are checked into git, and they are only generated by the build if the `marble-diagrams` profile is activated. However I've also added something to the generation process that outputs a file containing the hashes of all the input and output files to the marble diagram generation process, then I've added an additional task that reads this file, and checks all the hashes, to make sure they match. This then runs when you run `mvn verify`, regardless of what profile is activated.

What this means is if someone modifies a diagram, but forgets to generate the diagrams or check the updated diagrams into CI, the build will fail, so the PR build will fail and the release will also fail. Meanwhile, builds can still be done in the CI environment because the diagrams are checked into git, and the main build no longer depends on Chrome or its dependencies.

**Comment by cescoffier** [comment]
+1

**Pull request merged**
